server:
  port: 8080

milvus:
  host: localhost
  port: 19530

ollama:
  base-url: http://localhost:11434
  model-name: deepseek-r1:7b
  embedding-model: nomic-embed-text
  timeout: 300

spring:
  application:
    name: ollama-chat-demo
